# NumPy Industrial Use Cases – Full Structured Version

This notebook includes **Problem Statement**, **Industrial Context**, **Input/Output**, **Code**, **Explanation**, and **Key Takeaways** for each use case.

## **Use Case 1 — High-Performance Numerical Computation**

### **1. Problem Statement**
Efficiently apply mathematical operations to large datasets without Python loops.

### **2. Industrial Context**
Used in IoT pipelines, financial tick data processing, simulation engines, and streaming analytics.

### **3. Input / Output**
- **Input:** Numeric array
- **Output:** Each value doubled

### **4. Code Example**

In [1]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
output = data * 2
output

array([ 20,  40,  60,  80, 100])

### **5. Explanation**
NumPy vectorizes operations, executing them in optimized C loops instead of Python loops.

### **6. Key Takeaways**
- Vectorization speeds up computation
- Cleaner and more scalable than loops

## **Use Case 2 — Statistical Analysis of Time-Series Data**

### **1. Problem Statement**
Compute summary statistics from continuous data.

### **2. Industrial Context**
Used in forecasting, quality control, anomaly detection, and monitoring dashboards.

### **3. Input / Output**
- **Input:** 1D temperature readings
- **Output:** Mean, max, min, standard deviation

### **4. Code Example**

In [2]:
import numpy as np
temps = np.array([30, 32, 31, 29, 33, 28, 30])
temps.mean(), temps.max(), temps.min(), temps.std()

(30.428571428571427, 33, 28, 1.5907898179514348)

### **5. Explanation**
NumPy provides optimized statistical functions that work on arrays of any size instantly.

### **6. Key Takeaways**
- Ideal for real-time analytics
- Built-in statistical functions save time

## **Use Case 3 — Matrix Operations for Machine Learning**

### **1. Problem Statement**
Perform matrix multiplication required for ML algorithms and transformations.

### **2. Industrial Context**
Powers ML training pipelines, neural networks, and computer graphics.

### **3. Input / Output**
- **Input:** Two 2x2 matrices
- **Output:** Matrix-multiplied result

### **4. Code Example**

In [3]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B

array([[19, 22],
       [43, 50]])

### **5. Explanation**
NumPy uses optimized BLAS (Basic Linear Algebra Subprograms) libraries for matrix multiplication.

### **6. Key Takeaways**
- Foundation of ML math
- Highly optimized for speed

## **Use Case 4 — Synthetic Data Generation for Testing**

### **1. Problem Statement**
Generate artificial datasets for testing without real user data.

### **2. Industrial Context**
Used for load testing, ML prototyping, and secure synthetic pipelines.

### **3. Input / Output**
- **Input:** Range specification
- **Output:** 1000 random integers

### **4. Code Example**

In [4]:
import numpy as np
scores = np.random.randint(0, 101, size=1000)
scores[:10]

array([71, 30, 58, 94, 56, 28, 20, 37, 82, 78])

### **5. Explanation**
Random generation tools allow safe and fast dataset creation.

### **6. Key Takeaways**
- No production data required
- Supports various distributions

## **Use Case 5 — Data Filtering & Conditional Extraction**

### **1. Problem Statement**
Extract values matching a condition from an array.

### **2. Industrial Context**
Used in anomaly detection, rule filtering, and preprocessing pipelines.

### **3. Input / Output**
- **Input:** Random integer array
- **Output:** Elements above threshold

### **4. Code Example**

In [5]:
import numpy as np
data = np.random.randint(1, 100, size=20)
data, data[data > 50]

(array([93, 41, 75, 36, 22, 11, 60, 17, 36, 29, 62, 80, 59, 31, 64, 17, 56,
        40,  4, 50]),
 array([93, 75, 60, 62, 80, 59, 64, 56]))

### **5. Explanation**
Boolean masks provide a fast replacement for filtering loops.

### **6. Key Takeaways**
- Essential for data cleaning
- Very fast filtering operations

## **Use Case 6 — Reshaping Arrays**

### **1. Problem Statement**
Convert 1D arrays into structured 2D shapes.

### **2. Industrial Context**
Used in ML preprocessing, image processing, and ETL reshaping.

### **3. Input / Output**
- **Input:** 1D array of length 12
- **Output:** 3×4 matrix

### **4. Code Example**

In [6]:
import numpy as np
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### **5. Explanation**
`.reshape()` reorganizes memory without copying.

### **6. Key Takeaways**
- Critical for ML models
- Memory-efficient arrays

## **Use Case 7 — Columnar Data Processing (Tabular Data)**

### **1. Problem Statement**
Extract columns for analysis.

### **2. Industrial Context**
Used in BI dashboards, ML preprocessing, and ETL pipelines.

### **3. Input / Output**
- **Input:** 2D array of features
- **Output:** Column stats

### **4. Code Example**

In [7]:
import numpy as np
people = np.array([
    [25,170,65],
    [32,175,72],
    [29,168,70],
    [40,180,85]
])
people[:,1].mean(), people[:,0].max()

(173.25, 40)

### **5. Explanation**
Column slicing is extremely fast and intuitive.

### **6. Key Takeaways**
- Works like a fast spreadsheet
- Great for analytics workflows

## **Use Case 8 — Concatenation & Splitting Arrays**

### **1. Problem Statement**
Merge or split arrays efficiently.

### **2. Industrial Context**
Used in dataset creation, feature engineering, and train/test splits.

### **3. Input / Output**
- **Input:** Two arrays / one large array
- **Output:** Concatenated or split arrays

### **4. Code Example**

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
combined = np.hstack((a,b))
splits = np.split(np.arange(10),2)
combined, splits

(array([1, 2, 3, 4, 5, 6]), [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])])

### **5. Explanation**
Stacking and splitting are key in ETL pipelines.

### **6. Key Takeaways**
- Efficient merging and partitioning
- Clean syntax

## **Use Case 9 — Handling Missing Data (NaN Cleaning)**

### **1. Problem Statement**
Detect and replace missing values.

### **2. Industrial Context**
Used in ML preprocessing, data warehousing, and ETL cleaning.

### **3. Input / Output**
- **Input:** Array with NaN
- **Output:** Cleaned array

### **4. Code Example**

In [9]:
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
mean = np.nanmean(arr)
arr[np.isnan(arr)] = mean
arr

array([1.  , 2.  , 3.25, 4.  , 3.25, 6.  ])

### **5. Explanation**
`np.nanmean()` ignores NaNs and prevents crashes.

### **6. Key Takeaways**
- Essential for real datasets
- Prevents ML pipeline failures